name: build-codeblocks

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            p7zip
            git
            hunspell
            zip
            mingw-w64-i686-wxwidgets3.2-common
            mingw-w64-i686-wxwidgets3.2-msw
            mingw-w64-i686-wxwidgets3.2-msw-cb_headers
            mingw-w64-i686-toolchain
            base-devel

      - name: build CodeBlocks
        shell: msys2 {0}
        id: buildcb
        run: ./build.sh
        
      - name: release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.buildcb.outputs.RELEASE_NAME }}
          release_name: ${{ steps.buildcb.outputs.RELEASE_NAME }}
          body: |
            wxWidgets v${{ steps.buildcb.outputs.WXMSW_VERSION }}
            CodeBlocks r${{ steps.buildcb.outputs.CBREV_NO }}

      - name: upload
        id: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ steps.buildcb.outputs.OUTPUT_BINARY }}
          asset_name: ${{ steps.buildcb.outputs.OUTPUT_NAME }}
          asset_content_type: application/x-7z-compressed
