name: build-codeblocks

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32

      - shell: msys2 {0}
        run: |
          pacman -Syy
          pacman -S --noconfirm  wget git
          wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.5/wxWidgets-3.2.5.tar.bz2
          tar -jxf ./wxWidgets-3.2.5.tar.bz2
          git clone https://github.com/arnholm/codeblocks_sfmirror.git
          cp -f ./setup.h ./wxWidgets-3.2.5/include/wx/msw/
          cp -f ./config.gcc ./wxWidgets-3.2.5/build/msw/
          cmd
          cd wxWidgets-3.2.5\build\msw
          mingw32-make -f makefile.gcc setup_h
          mingw32-make -f makeflie.gcc -j8
